name: smart_detector
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: "3.5.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  go_router: ^14.2.7
  dartz: ^0.10.1
  get_it: ^7.7.0
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter_gen:
  output: lib/common/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
    
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Black.ttf
        - asset: assets/fonts/Inter_28pt-BlackItalic.ttf
        - asset: assets/fonts/Inter_28pt-Bold.ttf
        - asset: assets/fonts/Inter_28pt-BoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter_28pt-Italic.ttf
        - asset: assets/fonts/Inter_28pt-Light.ttf
        - asset: assets/fonts/Inter_28pt-LightItalic.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
        - asset: assets/fonts/Inter_28pt-MediumItalic.ttf
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
        - asset: assets/fonts/Inter_28pt-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter_28pt-Thin.ttf
        - asset: assets/fonts/Inter_28pt-ThinItalic.ttf
